spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fuelspot_db?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ejjun516@gmail.com
    password: dbnfyswsbcuusalx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


opinet:
  api-key: ${OPINET_API_KEY}

jwt:
  secret: ${JWT_SECRET}
